spring:
    application:
        name: xiaomaolv
    datasource:
        username: root
        password: yan.960807
        url: jdbc:mysql://172.81.203.18:3306/xiaomaolv?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
        driver-class-name: com.mysql.jdbc.Driver
server:
    port: 8080
mybatis:
    mapper-locations: classpath:mappers/*.xml
    type-aliases-package: com.xiaobo.xiaomaolv.entity

logging:
    level:
        com.xiaobo.smartmonkey.dao: DEBUG
